export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function ProductsLayout({ children }) {
  return (
    <main className={'min-h-screen'}>
      {children}
    </main>
  );
}
